name: Manual Approval
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: trstringer/manual-approval@v1
       with:
          secret: ${{ github.TOKEN }}
          approvers: DominatorGG
          minimum approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
      
     - name: Run a one-line script
       run: echo Hello, world!
